# NUMPY

In [4]:
# Numpy is a library. 
import numpy as np
list1 = [1,2,34,3,4,555]

arr1 = np.array(list1)

In [5]:
list1

[1, 2, 34, 3, 4, 555]

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1

array([  1,   2,  34,   3,   4, 555])

In [8]:
arr2 = np.array([434,2343,24223,6452,223,5577,2])

In [9]:
arr2

array([  434,  2343, 24223,  6452,   223,  5577,     2])

In [12]:
arr2.ndim     # "ndim"  # of dimensions or Axises

1

In [13]:
arr2.shape   # "shape" of of elements each axis has

(7,)

In [14]:
arr2.size     # "size" total # of elments in the array

7

In [16]:
arr5 = np.array([[3,4,3,4,4,3], [343,343,243,234,112,22], [4,24,24,3,5,3]])

In [17]:
arr5

array([[  3,   4,   3,   4,   4,   3],
       [343, 343, 243, 234, 112,  22],
       [  4,  24,  24,   3,   5,   3]])

In [18]:
print(arr5.ndim)
print(arr5.shape)
print(arr5.size)

2
(3, 6)
18


In [19]:
# 3 Axises

arr6 = np.array([[[3,4,3,4,4,3], [343,343,243,234,112,22], [4,24,24,3,5,3]],[[3,4,3,4,4,3], [343,343,243,234,112,22], [4,24,24,3,5,3]],[[3,4,3,4,4,3], [343,343,243,234,112,22], [4,24,24,3,5,3]],[[3,4,3,4,4,3], [343,343,243,234,112,22], [4,24,24,3,5,3]]])

In [20]:
arr6

array([[[  3,   4,   3,   4,   4,   3],
        [343, 343, 243, 234, 112,  22],
        [  4,  24,  24,   3,   5,   3]],

       [[  3,   4,   3,   4,   4,   3],
        [343, 343, 243, 234, 112,  22],
        [  4,  24,  24,   3,   5,   3]],

       [[  3,   4,   3,   4,   4,   3],
        [343, 343, 243, 234, 112,  22],
        [  4,  24,  24,   3,   5,   3]],

       [[  3,   4,   3,   4,   4,   3],
        [343, 343, 243, 234, 112,  22],
        [  4,  24,  24,   3,   5,   3]]])

In [21]:
print(arr6.ndim)
print(arr6.shape)
print(arr6.size)

3
(4, 3, 6)
72


# Indexing

In [22]:
arr10 = np.array([10,24,41,4,67,53,224,24,2211,11,666,332])

In [24]:
arr10[1]

24

In [26]:
arr10[9]

11

In [27]:
arr10[-3]

11

# Slicing

In [29]:
arr10[2:5:1]

array([41,  4, 67])

In [30]:
arr10[1:8:2]

array([24,  4, 53, 24])

In [31]:
arr10[0:2]

array([10, 24])

In [32]:
arr10

array([  10,   24,   41,    4,   67,   53,  224,   24, 2211,   11,  666,
        332])

In [33]:
arr10[::-1]     #Array reversed

array([ 332,  666,   11, 2211,   24,  224,   53,   67,    4,   41,   24,
         10])

In [34]:
arr10[::-2]

array([332,  11,  24,  53,   4,  24])

In [35]:
arr10[-2::-1]

array([ 666,   11, 2211,   24,  224,   53,   67,    4,   41,   24,   10])

In [36]:
l1 = [1,5]   # set up a list which will look for 1st and 5th index pos

arr10[l1]   # l1 will find 1st and 5th index value for "arr10"  which is 24 and 53

array([24, 53])